/**
 * lockstep-lib — shared definition of the faijs package-family lockstep rule.
 *
 * The family is every publishable `@faicad/*` package under `packages/`. They all
 * ship under ONE version, declared once in the root `package.json`
 * (`config.faijsVersion`) and mirrored into every family member's `version` field
 * by `set-version.mjs`. `check-lockstep.mjs` enforces both halves of the rule:
 *
 *   1. version equality — every family member's `version` == `config.faijsVersion`;
 *   2. range coherence — every registry-range `@faicad/*` dependency points at the
 *      family version line (`^<major>.<minor>.0`).
 *
 * The second half exists because of a 2026-09 incident: `fai_cq_gears` had bumped
 * itself to 0.16.x while its `dependencies` still declared `"@faicad/cq-compat":
 * "^0.14.0"`, so a CDN build resolved a stale `cq-compat@0.14.1` and the package
 * graph broke. Version equality alone cannot catch that; both halves are needed.
 */
import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
export const packagesDir = join(repoRoot, 'packages')

/**
 * Packages excluded from the family. They are `private: true` and never published,
 * so their version fields are not release-relevant. The `private` filter in
 * `readFamily` already covers them; the explicit set documents the intent and
 * guards against a package being un-privatized by accident.
 */
export const FAMILY_EXCLUDE = new Set([
  '@faicad/faijs-fixtures',
  '@faicad/faijs-tests',
  '@faicad/faijs-demo',
])

/** Local path protocols: resolved from disk, never from the registry. */
export const LOCAL_PROTOCOLS = ['file:', 'workspace:', 'link:']

/** package.json sections scanned for `@faicad/*` ranges. */
export const DEP_SECTIONS = ['dependencies', 'peerDependencies', 'devDependencies']

/** @param {string} range @returns {boolean} */
export function isLocalRange(range) {
  return typeof range === 'string' && LOCAL_PROTOCOLS.some((p) => range.startsWith(p))
}

/** The single allowed registry range for a given family version, e.g. 0.16.1 -> `^0.16.0`. */
export function expectedRange(version) {
  const m = /^(\d+)\.(\d+)\./.exec(String(version))
  if (!m) return null
  return `^${m[1]}.${m[2]}.0`
}

/** @returns {object} the root package.json */
export function readRootPackage() {
  return JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'))
}

/**
 * The lockstep family version: root `config.faijsVersion`. The root package is
 * `private`, so its own `version` field is not the release version — `config.faijsVersion` is.
 * @returns {string|null} the declared family version, or null if absent/invalid
 */
export function familyVersion(rootPkg = readRootPackage()) {
  const v = rootPkg?.config?.faijsVersion
  return typeof v === 'string' && /^\d+\.\d+\.\d+$/.test(v) ? v : null
}

/**
 * The CDN release pin mirror (`cdn/versions.json`), generated by `gen-importmap.mjs`
 * and consumed by the plan-b exact-pin browser lib loader. It is a second home for
 * the same version fact, so the guard asserts it tracks the family.
 * @returns {Record<string, string>|null} the parsed map, or null when the file is absent
 */
export function readCdnVersions() {
  const p = join(repoRoot, 'cdn', 'versions.json')
  if (!existsSync(p)) return null
  return JSON.parse(readFileSync(p, 'utf8'))
}

/**
 * Read every `@faicad/*` workspace package under `packages/`.
 * @param {{ includePrivate?: boolean }} [opts] - include `private: true` packages
 *   (fixtures / tests / demo) in the result; off by default.
 * @returns {Map<string, { name: string, dir: string, version: string, private: boolean, pj: object }>}
 */
export function readFamily({ includePrivate = false } = {}) {
  const out = new Map()
  for (const entry of readdirSync(packagesDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const pjPath = join(packagesDir, entry.name, 'package.json')
    if (!existsSync(pjPath)) continue
    const pj = JSON.parse(readFileSync(pjPath, 'utf8'))
    if (!pj.name || !pj.name.startsWith('@faicad/')) continue
    const isPrivate = pj.private === true
    if (isPrivate && !includePrivate) continue
    if (!includePrivate && FAMILY_EXCLUDE.has(pj.name)) continue
    out.set(pj.name, {
      name: pj.name,
      dir: entry.name,
      version: String(pj.version ?? ''),
      private: isPrivate,
      pj,
    })
  }
  return out
}

/**
 * The two lockstep rules, as a pure function over an in-memory family.
 *
 * Split out of `check-lockstep.mjs` so the rules can be exercised against synthetic
 * package sets (`--self-test`) instead of only against whatever the working tree
 * happens to contain — a guard that has never been seen to fail is not evidence.
 *
 * @param {Map<string, {name: string, version: string, pj: object}>} family
 * @param {string|null} declared - the root `config.faijsVersion`
 * @param {Record<string, string>|null} [cdnVersions] - parsed `cdn/versions.json`
 *   (the release-path version mirror); rule 3 is skipped when null/undefined.
 * @returns {string[]} human-readable violations, empty when the family is aligned
 */
export function collectViolations(family, declared, cdnVersions = null) {
  const violations = []

  // Rule 1: version equality against the single source of truth.
  if (!declared) {
    violations.push(
      'root package.json config.faijsVersion is missing or not a valid MAJOR.MINOR.PATCH — declare the family version there',
    )
  } else {
    for (const [name, info] of family) {
      if (info.version !== declared) {
        violations.push(
          `${name} is ${info.version || '(no version)'} but the family version is ${declared} ` +
            `— run \`node scripts/set-version.mjs ${declared}\` to align the whole family`,
        )
      }
    }
  }

  // Rule 2: every registry-range @faicad/* entry points at the family version line.
  for (const [name, info] of family) {
    for (const section of DEP_SECTIONS) {
      for (const [dep, range] of Object.entries(info.pj[section] ?? {})) {
        if (!dep.startsWith('@faicad/')) continue
        if (isLocalRange(range)) continue
        const target = family.get(dep)
        if (!target) continue // not a family member (external package)
        const expected = expectedRange(target.version)
        if (!expected) {
          violations.push(
            `${name} -> ${dep} (${section}): cannot derive the expected range from target version "${target.version}"`,
          )
          continue
        }
        if (range !== expected) {
          violations.push(
            `${name} (${info.version}) -> ${dep} (${section}): "${range}" but ${dep} is ${target.version}; ` +
              `expected "${expected}" — a stale range makes a CDN build resolve an old ${dep}`,
          )
        }
      }
    }
  }

  // Rule 3: the CDN release pin mirror tracks the family version.
  if (cdnVersions) {
    for (const [name, info] of family) {
      const pinned = cdnVersions[name]
      if (pinned === undefined) {
        violations.push(
          `cdn/versions.json has no pin for ${name} — run \`node scripts/gen-importmap.mjs\` ` +
            `(the plan-b exact-pin loader would fall back to unpinned resolution for it)`,
        )
      } else if (pinned !== info.version) {
        violations.push(
          `cdn/versions.json pins ${name}@${pinned} but the package is ${info.version} — ` +
            `run \`node scripts/gen-importmap.mjs\``,
        )
      }
    }
  }

  return violations
}
