/**
 * Phase 0.4 探针（内核侧）：计划 §7 测定项第 **1** 项、第 **7** 项，外加布尔/直接编辑
 * 归账方式的实测（第 7 项的直接延伸，本文件最重要的产出）。
 *
 * 见 `docs/plans/2026-09-22-topology-identity-development-plan.md` §7。每一项的分支已预置，
 * 本文件只负责**测出事实、选分支**。探针落成 `.test.ts`（AGENTS.md 铁律）。
 *
 * | # | 待测事实 | 分支 A | 分支 B | 实测 |
 * |---|---|---|---|---|
 * | 1 | `heal`/`simplify`/`autoHeal`/`fixShape`/`healSolid` 是否真有内核历史 | 有 → `kernel` | 无 → `unmodeled` | **B（无）** |
 * | 7 | `cut` 的孔壁应挂哪个 `origin` | 符合准则 → 留档 | 不符 → 修 | **不符：准则是伪需求（见下）** |
 *
 * ## 一、第 1 项：为什么"内核没有"是可测的事实
 *
 * 内核的历史能力只能通过 `*WithHistory` 变体获得（没有"给我上一次运算的历史"这种通用查询）。
 * ⇒ 可测判据 = **历史族名单里有没有 healing 家族的成员**。本文件枚举内核对象的
 * **own + inherited** 全部函数名（embind 包装对象的方法可能挂在原型上，只 `Object.keys`
 * 会漏），再断言历史族恰为已知 12 个、且其中无一属 healing。
 * ⚠️ 这是**正向守卫**：将来 occt-wasm 若补上 `healWithHistory`，断言变红 ⇒ 分支须回到 A。
 *
 * GOTCHA（第二次运行才发现）：判"是否属 healing"必须**先剥掉 `WithHistory` 后缀再匹配**。
 * 直接对全名跑 `/sew/i` 会把 **`fu·seW·ithHistory`** 判成缝合类历史——那个 "sew" 是跨词界
 * 拼出来的巧合。
 *
 * ⚠️ 与 `evolution-bindings.test.ts` 的分工：那里断言 12 个历史变体**存在且行为正确**；
 * 这里断言历史族**只有这 12 个**（负向完整性）。
 *
 * ## 二、第 7 项：实测结果**与计划原文不符**，而且原文的靶子根本不存在
 *
 * 计划原文：**孔壁是 `cut` 的新造面 ⇒ 挂 `cut` 的 `StmtId`、`role = hole:<j>`**。
 * 实测（`cut(20³ box, ⌀6 贯穿圆柱)`）：
 *
 * | 结果面 | 实测归账 | 含义 |
 * |---|---|---|
 * | R6 `cylinder`（**就是孔壁**） | `b.modified`：工具侧面 `B0 → R6` | 孔壁是**工具侧面的改型幸存者**，不是新造面 |
 * | R2 / R4 `plane` | `a.modified`：box 顶/底 `A5→R2`、`A4→R4` | 穿孔后仍是一张面（带孔平面） |
 * | R0/R1/R3/R5 `plane` | 不在任何 `modified` 里，且 hash 与 A0/A1/A2/A3 **逐字相同** | 未受影响的四个侧面：**原样幸存** |
 * | 工具端面 B1/B2 | `b.deleted` | 被删除，无后继 |
 *
 * ⇒ **`cut` 的结果面里"新造面"是空集。** `hole:<j>` 是伪需求：孔壁已有权威身份
 * （工具圆柱侧面 `B0` 的后继），再伪造一个 `hole:<j>` 会与内核权威冲突，并丢掉
 * "这张壁就是那个圆柱的侧面"这个更有用的信息。
 *
 * ## 三、结果面的**三种命运**（本文件的中心结论，两个 op 交叉验证）
 *
 * | 命运 | 判据（可执行） | cut 实测 | fillet 实测 |
 * |---|---|---|---|
 * | **原样幸存** | hash ∈ 输入面 hash 集合（**hash 逐字不变**） | 4 个未动侧面 | R3 / R6 |
 * | **改型幸存** | hash ∈ 某输入的 `modified` 输出（可 1→N） | R2/R4（A 侧）、R6（B 侧） | R0/R1/R4/R5 |
 * | **新造** | 既不在输入 hash 集合、也不在任何 `modified` 输出里 | **空集** | **R2（过渡圆柱面）** |
 *
 * 判据必须是"补集 **再减掉 hash 未变者**"：fillet 的 R3/R6 就**不在** `modified` 输出里
 * （OCCT 没上报未受影响的面），只按补集会把它们误判成新造面。
 *
 * ⇒ 由此得到两条对 Phase 3 有约束力的结论：
 * 1. **`gen:fillet:0` 这类派生词汇是必需的**——倒角/圆角过渡面在权威映射里没有任何来源
 *    （`generated` 也是空的，见下），只能由构造语义命名（G3 L1/L6 的目标词表方向正确）。
 * 2. **`hole:<j>` 必须删掉**（G3 L2 的目标词表要改，见该文件）。
 *
 * ## 四、`generated` 桶不可用于定位新造面（且官方文档的编码说明是错的）
 *
 * 实测三点：
 * 1. **编码**：`generated` 与 `modified` **同构**，是分段映射 `[inHash, count, outHash…] × N`，
 *    键与 `modified` **完全相同**（cut 实测键 = A4/A5/B0）。occt-wasm 的
 *    `dist/types.d.ts:229` 写 "New face hashes generated by the operation"、
 *    faijs 的 `brep/engine/types.ts:84-85` 写"操作新生成的面 hash"，**都把它当扁平数组描述**——
 *    按扁平数组读会把 count 字段当成 hash。**本项为文档缺陷，已在两处改正。**
 * 2. **语义**：cut 里 12 个 hash、结果里 **0 个存活**（指向被丢弃的中间形，如孔内被切掉的圆片）；
 *    fillet/fuse 里**整个桶为空**。
 * 3. ⇒ `decodeHashEvolution` 刻意不把 `generated` 引进 role 传播（`face-evolution.ts:136`）
 *    **是对的**，实测支持；把新造面交给 `construct`/派生词汇也是对的。
 *
 * ## 五、1→N 分裂的顺序跨重放稳定（可作子角色命名的根据）
 *
 * `fuse(box, box+5x)` 里 8 个输入面各裂成 2 个后继（结果 14 面、`deleted` 两个）。
 * 跑两遍，**分段键集、各段后继的中心点序列、`deleted` 集合、结果面数全部逐字相同**；
 * 后继顺序还呈空间有序（如 y=0 面 → `[2.5,0,5]`、`[7.5,0,5]`，沿 x 递增）。
 * ⇒ 1→N 的后继可以用**段内下标**稳定命名，不必另找判据。
 *
 * ## 六、已顺带钉住的三个现有代码断言
 *
 * - `propagateOriginRoles` 的读法 `modified.get(h) ?? [h]`（"不在 map ⇒ 未变 ⇒ 原样"）
 *   **与实测一致**：未见面的 hash 逐字幸存（本文件断言 `A0 === R0` 一族）。
 * - `decodeHashEvolution` 头注"generated 对布尔实测 0 个存活"：**成立**（12/0）。
 * - ⚠️ **但"未变"有两种上报形态**：fillet 里 R0/R4 被上报为 `0->[0]`、`4->[4]` 的**自映射**，
 *   而 R3/R6 **整个不上报**。两种形态都表示未变，读法必须同时容纳
 *   （`?? [h]` 恰好容纳，属**巧合的正确**——故本文件把它钉住）。
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { initOcctWasm, getKernel } from '../../occt-kernel/occtKernel'
import { HASH_UPPER_BOUND, splitHashEvolutionByOrigin, decodeHashEvolution } from '../face-evolution'
import type { BrepHandle } from './types'
import type { BrepEngineApi } from './primitives'

let kernel: BrepEngineApi

beforeAll(async () => {
  await initOcctWasm()
  kernel = getKernel() as unknown as BrepEngineApi
}, 120000)

/** occt-wasm@3.8.4 暴露的全部 `*WithHistory`（dist/index.d.ts:458-472）。 */
const ALL_WITH_HISTORY = [
  'fuseWithHistory',
  'cutWithHistory',
  'intersectWithHistory',
  'filletWithHistory',
  'chamferWithHistory',
  'translateWithHistory',
  'rotateWithHistory',
  'mirrorWithHistory',
  'scaleWithHistory',
  'shellWithHistory',
  'offsetWithHistory',
  'thickenWithHistory',
] as const

/** healing 家族的名字判据（**作用在剥掉 `WithHistory` 后的词干上**，见文件头注 GOTCHA）。 */
const HEALING_STEM_RE = /heal|simplif|repair|sew|^fix/i

/**
 * 收集对象的 **own + 原型链** 全部属性名。
 *
 * 只 `Object.keys` 会漏掉 embind 包装对象挂在原型上的方法——而"漏掉"在本文件里会
 * **伪装成"内核没有历史 API"**，正好是待测事实本身，所以枚举必须完整（宁多勿少）。
 * @param obj - the object whose property names to collect.
 * @returns every own and inherited property name, de-duplicated.
 */
function allPropertyNames(obj: unknown): string[] {
  const names = new Set<string>()
  let cur = obj as object | null
  while (cur !== null && cur !== Object.prototype) {
    for (const n of Object.getOwnPropertyNames(cur)) names.add(n)
    cur = Object.getPrototypeOf(cur) as object | null
  }
  return [...names]
}

/** 面 hash 列表（与 `getSubShapes(…,'face')` 按下标一一对应）。 */
function faceHashes(shape: BrepHandle): number[] {
  return Array.from(kernel.subShapeHashes(shape, 'face', HASH_UPPER_BOUND))
}

/** hash → 该面句柄（靠"下标一一对应"这一契约，见 face-evolution.ts 头注）。 */
function faceHandleOf(shape: BrepHandle, hash: number): BrepHandle {
  const handles = kernel.getSubShapes(shape, 'face')
  const idx = faceHashes(shape).indexOf(hash)
  if (idx < 0) throw new Error(`[probe] hash ${hash} 不属于该形状`)
  return handles[idx]
}

/** 面类型（'plane' / 'cylinder' / …）—— 几何语义的最小可观测。 */
function typeOf(shape: BrepHandle, hash: number): string {
  return kernel.surfaceType(faceHandleOf(shape, hash))
}

/**
 * 解码分段映射 `[inHash, count, outHash…] × N`。
 *
 * ⚠️ **`modified` 与 `generated` 都是这个格式**（见文件头注第四节）。
 * `deleted` 是扁平 hash 数组（实测）。
 * @param m - the segmented array.
 * @returns [inHash, outHashes] pairs in reported order.
 */
function decodeSegmented(m: number[]): Array<[number, number[]]> {
  const out: Array<[number, number[]]> = []
  let i = 0
  while (i < m.length) {
    const count = m[i + 1]
    out.push([m[i], m.slice(i + 2, i + 2 + count)])
    i += 2 + count
  }
  return out
}

/** 某形状若干面的"中心点"序列（保留 3 位小数，用于比较跨重放顺序）。 */
function centersOf(shape: BrepHandle, hashes: readonly number[]): number[][] {
  const handles = kernel.getSubShapes(shape, 'face')
  const all = faceHashes(shape)
  return hashes.map((h) => {
    const c = kernel.getSurfaceCenterOfMass(handles[all.indexOf(h)])
    return [Math.round(c.x * 1000) / 1000, Math.round(c.y * 1000) / 1000, Math.round(c.z * 1000) / 1000]
  })
}

/** 标准场景：20³ box + 贯穿其中心的 ⌀6 圆柱刀。 */
function cutThroughHole(): {
  box: BrepHandle
  tool: BrepHandle
  hashesA: number[]
  hashesB: number[]
  evo: ReturnType<BrepEngineApi['cutWithHistory']>
} {
  const box = kernel.makeBox(20, 20, 20)
  const cyl = kernel.makeCylinder(3, 30)
  // box 占 [0..20]³，圆柱轴默认在原点 ⇒ 平移到 (10,10,-5) 即贯穿上下底
  const tool = kernel.translate(cyl, 10, 10, -5)
  kernel.release(cyl)

  const hashesA = faceHashes(box)
  const hashesB = faceHashes(tool)
  const evo = kernel.cutWithHistory(box, tool, [...new Set([...hashesA, ...hashesB])], HASH_UPPER_BOUND)
  return { box, tool, hashesA, hashesB, evo }
}

// ─────────────────────────────────────────────────────────────────────────────

describe('§7 第 1 项：heal 家族是否有内核历史（分支 B：无）', () => {
  it('内核历史族恰为 12 个，且无一属 healing（heal / simplify / fix / sew / repair）', () => {
    const names = allPropertyNames(kernel)
    const historyFamily = names.filter((n) => n.endsWith('WithHistory')).sort()

    // 负向完整性：族里只有这 12 个（内核多出成员 ⇒ 本断言变红 ⇒ 重评第 1 项分支）
    expect(historyFamily).toEqual([...ALL_WITH_HISTORY].sort())

    // 待测事实：历史族里没有 healing 家族的成员
    const healingHistory = historyFamily.filter((n) => HEALING_STEM_RE.test(n.replace(/WithHistory$/, '')))
    expect(healingHistory).toEqual([])
  })

  it('内核上确实存在 healing 函数本体（阳性对照：不是"函数名都不在"导致的假绿）', () => {
    const healingBodies = allPropertyNames(kernel).filter(
      (n) => !n.endsWith('WithHistory') && HEALING_STEM_RE.test(n),
    )
    expect(healingBodies.length).toBeGreaterThan(0)
  })
})

describe('§7 第 7 项：cut 的孔壁归账（分支 B：原文不符，hole:<j> 是伪需求）', () => {
  it('孔壁是「工具侧面的改型幸存者」，不是 cut 的新造面', () => {
    const { box, tool, hashesA, hashesB, evo } = cutThroughHole()
    expect(kernel.isValid(evo.result)).toBe(true)

    const resultHashes = faceHashes(evo.result)
    expect(resultHashes).toHaveLength(7) // 6 个 box 面（顶/底穿孔后仍是单面）+ 1 孔壁

    // 本场景唯一的圆柱面就是孔壁
    const cylinders = resultHashes.filter((h) => /cylind/i.test(typeOf(evo.result, h)))
    expect(cylinders).toHaveLength(1)
    const holeWall = cylinders[0]

    const { a, b } = splitHashEvolutionByOrigin(evo, hashesA, hashesB)
    expect(hashesB).toHaveLength(3) // 工具：侧面 + 两端面
    const toolSide = hashesB.find((h) => /cylind/i.test(typeOf(tool, h)))!

    // 待测事实（本文件最重要的产出）：孔壁 = 工具侧面 B0 的后继
    expect(b.modified.get(toolSide)).toEqual([holeWall])
    expect(outputsOfModified(a)).not.toContain(holeWall)

    kernel.release(box)
    kernel.release(tool)
    kernel.release(evo.result)
  })

  it('cut 的结果面里"新造面"是空集（三种命运判定下）', () => {
    const { box, tool, hashesA, hashesB, evo } = cutThroughHole()
    const resultHashes = faceHashes(evo.result)
    const inputHashes = new Set([...hashesA, ...hashesB])
    const modifiedOut = new Set(outputsOfModified2(evo.modified))

    const verdicts = resultHashes.map((h) =>
      modifiedOut.has(h) ? 'modified' : inputHashes.has(h) ? 'unchanged' : 'NEW',
    )
    // 4 个未动侧面（unchanged，hash 逐字幸存）+ 2 个带孔平面 + 1 个孔壁（皆 modified）
    expect(verdicts.filter((v) => v === 'unchanged')).toHaveLength(4)
    expect(verdicts.filter((v) => v === 'modified')).toHaveLength(3)
    expect(verdicts.filter((v) => v === 'NEW')).toEqual([])

    kernel.release(box)
    kernel.release(tool)
    kernel.release(evo.result)
  })

  it('穿孔只改型 box 顶/底面；工具两端面进 deleted（无后继）', () => {
    const { box, tool, hashesA, hashesB, evo } = cutThroughHole()
    const { a, b } = splitHashEvolutionByOrigin(evo, hashesA, hashesB)

    expect([...a.modified.keys()].sort()).toEqual([hashesA[4], hashesA[5]].sort())
    const toolSide = hashesB.find((h) => /cylind/i.test(typeOf(tool, h)))!
    expect([...b.modified.keys()]).toEqual([toolSide])
    expect([...a.deleted]).toEqual([])
    expect([...b.deleted].sort()).toEqual(hashesB.filter((h) => h !== toolSide).sort())

    kernel.release(box)
    kernel.release(tool)
    kernel.release(evo.result)
  })

  it('未被触碰的面原样幸存：hash 在结果里逐字不变（钉住 propagateOriginRoles 的读法）', () => {
    const { box, tool, hashesA, hashesB, evo } = cutThroughHole()
    const { a } = splitHashEvolutionByOrigin(evo, hashesA, hashesB)
    const resultHashes = new Set(faceHashes(evo.result))

    for (const h of hashesA.slice(0, 4)) {
      expect(a.modified.has(h), `面 ${h} 不该被改型`).toBe(false)
      expect(resultHashes.has(h), `面 ${h} 应原样幸存（hash 不变）`).toBe(true)
    }

    kernel.release(box)
    kernel.release(tool)
    kernel.release(evo.result)
  })
})

describe('结果面三种命运的判定（cut / fillet 交叉验证）', () => {
  it('fillet 的过渡面是唯一真·新造面：不在输入 hash、也不在任何 modified 输出里', () => {
    const box = kernel.makeBox(20, 20, 20)
    const edges = kernel.getSubShapes(box, 'edge')
    const hashesA = faceHashes(box)
    const evo = kernel.filletWithHistory(box, [edges[0]], 3, hashesA, HASH_UPPER_BOUND)

    const resultHashes = faceHashes(evo.result)
    expect(resultHashes).toHaveLength(7) // 6 面去 2 个被裁 + 1 个过渡圆柱 = 7（两个相邻面各留一片）

    const inputHashes = new Set(hashesA)
    const modifiedOut = new Set(outputsOfModified2(evo.modified))
    const verdicts = resultHashes.map((h) =>
      modifiedOut.has(h) ? 'modified' : inputHashes.has(h) ? 'unchanged' : 'NEW',
    )

    // 恰 1 个新造面，且它就是过渡圆柱面
    const fresh = resultHashes.filter((_, i) => verdicts[i] === 'NEW')
    expect(fresh).toHaveLength(1)
    expect(typeOf(evo.result, fresh[0])).toMatch(/cylind/i)

    // 两个未受影响的平面：整个不上报（既不 modified 也不 deleted），hash 逐字幸存
    expect(verdicts.filter((v) => v === 'unchanged')).toHaveLength(2)
    // 四个被裁的面：上报为新 hash 的 modified 后继
    expect(verdicts.filter((v) => v === 'modified')).toHaveLength(4)

    kernel.release(box)
    kernel.release(evo.result)
  })

  it('fillet 的 deleted 与 generated 都是空桶（未受影响的面"不上报"，不是"删除"）', () => {
    const box = kernel.makeBox(20, 20, 20)
    const edges = kernel.getSubShapes(box, 'edge')
    const hashesA = faceHashes(box)
    const evo = kernel.filletWithHistory(box, [edges[0]], 3, hashesA, HASH_UPPER_BOUND)

    expect(evo.deleted).toEqual([])
    expect(evo.generated).toEqual([])
    // modified 只有 4 段 1:1（含 2 段自映射 0->[0]、4->[4]）
    expect(decodeSegmented(evo.modified)).toHaveLength(4)

    kernel.release(box)
    kernel.release(evo.result)
  })

  it('fuse 的 1→N 分裂：段内后继顺序跨重放逐字稳定（子角色命名可用段内下标）', () => {
    /** 跑一遍 fuse(box, box 沿 +x 平移 5)，返回各输入面 → 后继中心点序列。 */
    const run = (): { segs: Array<[number, number[][]]>; deleted: number[]; resultCount: number } => {
      const a = kernel.makeBox(10, 10, 10)
      const b0 = kernel.makeBox(10, 10, 10)
      const b = kernel.translate(b0, 5, 0, 0)
      kernel.release(b0)
      const hashesA = faceHashes(a)
      const hashesB = faceHashes(b)
      const evo = kernel.fuseWithHistory(a, b, [...new Set([...hashesA, ...hashesB])], HASH_UPPER_BOUND)

      const inputOrder = [...hashesA, ...hashesB]
      const segs: Array<[number, number[][]]> = decodeSegmented(evo.modified).map(([inHash, outs]) => [
        inputOrder.indexOf(inHash),
        centersOf(evo.result, outs),
      ])
      const out = {
        segs,
        deleted: evo.deleted.map((h) => inputOrder.indexOf(h)).sort(),
        resultCount: faceHashes(evo.result).length,
      }

      kernel.release(a)
      kernel.release(b)
      kernel.release(evo.result)
      return out
    }

    const r1 = run()
    const r2 = run()

    // 8 个输入面各裂成 2 个后继；2 个输入面被吞掉；结果 14 面
    expect(r1.segs).toHaveLength(8)
    for (const [, outs] of r1.segs) expect(outs).toHaveLength(2)
    expect(r1.deleted).toHaveLength(2)
    expect(r1.resultCount).toBe(14)

    // 待测事实：跨重放逐字稳定（分段键集 + 每段后继的中心点序列 + deleted + 面数）
    expect(r2.segs).toEqual(r1.segs)
    expect(r2.deleted).toEqual(r1.deleted)
    expect(r2.resultCount).toBe(r1.resultCount)
  })
})

describe('generated 桶：编码 / 语义 / 文档缺陷（不可用于定位新造面）', () => {
  it('generated 与 modified 同构（分段映射），键集完全相同', () => {
    const { box, tool, evo } = cutThroughHole()

    const modKeys = decodeSegmented(evo.modified).map(([k]) => k)
    const genKeys = decodeSegmented(evo.generated).map(([k]) => k)

    // 若按"扁平 hash 数组"读，会把 count 字段（=2）当成 hash；分段解码后键集与 modified 相同
    expect(genKeys).toEqual(modKeys)
    expect(evo.generated).toContain(2) // 分段编码里的 count 字段（扁平读法的陷阱所在）

    kernel.release(box)
    kernel.release(tool)
    kernel.release(evo.result)
  })

  it('generated 的 hash 在结果里 0 个存活（验证代码头注的既有断言）', () => {
    const { box, tool, evo } = cutThroughHole()
    const resultHashes = new Set(faceHashes(evo.result))

    expect(evo.generated.length).toBeGreaterThan(0) // 桶非空，断言才有信息量
    expect(evo.generated.filter((h) => resultHashes.has(h))).toEqual([])

    // decodeHashEvolution 刻意不把 generated 引进 role 传播（face-evolution.ts:136）
    // —— 实测支持：放进去也永远不会命中存活面。
    const hashEvo = decodeHashEvolution(evo)
    expect(hashEvo.modified.size).toBeGreaterThan(0)

    kernel.release(box)
    kernel.release(tool)
    kernel.release(evo.result)
  })
})

/** `modified`（分段）的输出面 hash 扁平集（按 splitHashEvolutionByOrigin 拆出的单侧版本）。 */
function outputsOfModified(a: { modified: ReadonlyMap<number, readonly number[]> }): number[] {
  const out: number[] = []
  for (const list of a.modified.values()) out.push(...list)
  return out
}

/** 原始分段 `modified` 的输出面 hash 扁平集（不拆 A/B）。 */
function outputsOfModified2(modified: number[]): number[] {
  return decodeSegmented(modified).flatMap(([, outs]) => outs)
}
